import { LegalLayout } from './LegalLayout';

export function Terms({ onBack }: { onBack: () => void }) {
  return (
    <LegalLayout title="Terms of Service" effective="May 6, 2026" onBack={onBack}>
      <Section title="1. The Service">
        <p>
          Mythos 0X Forge ("the Service") is a web application that analyzes images and short videos
          for indicators of AI generation, providing a probabilistic assessment and forensic
          breakdown. By using the Service, you agree to these Terms.
        </p>
      </Section>

      <Section title="2. Advisory output, not evidence">
        <p>
          <strong>The Service produces probabilistic estimates, not legal evidence.</strong>{' '}
          Confidence scores and findings are generated by automated detection models that have
          known false-positive and false-negative rates. We make no warranty that any verdict is
          correct, complete, or admissible in any legal, journalistic, or institutional
          proceeding. You are solely responsible for any decisions you make based on Service
          output.
        </p>
      </Section>

      <Section title="3. Acceptable use">
        <p>
          You may not use the Service to harass, dox, or target individuals; to circumvent the
          authentication of media you do not own or have rights to test; to build derivative
          datasets that would compete with the Service; or for any unlawful purpose. See our
          Acceptable Use Policy for the full list.
        </p>
      </Section>

      <Section title="4. Accounts and billing">
        <p>
          Free, Pro, and Max tiers gate compute via daily analysis limits. Subscriptions auto-renew
          at the chosen interval (monthly or yearly) until canceled. You may cancel at any time via
          the billing portal; access continues through the end of your paid period. Refund
          requests within seven (7) days of initial purchase are honored at our discretion.
        </p>
      </Section>

      <Section title="5. Content and ownership">
        <p>
          You retain all rights to media you upload. We process uploads transiently to produce a
          verdict; uploaded files are stored ephemerally for caching and may be retained up to
          thirty (30) days for abuse review. We do not train models on your uploads. We may
          retain non-identifying analysis metadata (verdict, model tag, timestamp) for service
          operation and abuse prevention.
        </p>
      </Section>

      <Section title="6. Third-party providers">
        <p>
          The Service routes uploads to detection providers and language-model narration providers
          ("Providers"). By submitting media, you authorize transmission of that media to such
          Providers under their respective terms. We do not control Provider retention policies and
          recommend you review them if processing sensitive content.
        </p>
      </Section>

      <Section title="7. No warranty">
        <p>
          The Service is provided "as is" without warranty of any kind, express or implied,
          including but not limited to warranties of merchantability, fitness for a particular
          purpose, or non-infringement. We do not guarantee uptime, accuracy, or fitness for any
          purpose involving real-world consequences.
        </p>
      </Section>

      <Section title="8. Limitation of liability">
        <p>
          To the maximum extent permitted by law, our aggregate liability for any claim arising
          out of or relating to the Service is limited to the greater of (a) the amount you paid
          us in the twelve (12) months preceding the claim, or (b) one hundred U.S. dollars
          ($100). We are not liable for indirect, incidental, consequential, or punitive damages.
        </p>
      </Section>

      <Section title="9. Termination">
        <p>
          We may suspend or terminate accounts that violate these Terms or the Acceptable Use
          Policy, or that we reasonably believe pose abuse risk. You may delete your account at any
          time; deletion removes your account record and active subscription but may retain
          minimal records as required for accounting and abuse prevention.
        </p>
      </Section>

      <Section title="10. Changes">
        <p>
          We may update these Terms from time to time. Material changes will be communicated by
          email to active subscribers and posted at this URL. Continued use after changes
          constitutes acceptance.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions about these Terms can be sent to{' '}
          <a className="text-ember-gold hover:text-ember-fire" href="mailto:legal@mythos0x.com">
            legal@mythos0x.com
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-7">
      <h2 className="mb-3 font-display text-lg font-semibold tracking-tight text-ember-gold">
        {title}
      </h2>
      <div className="text-[14px] leading-relaxed text-white/70">{children}</div>
    </section>
  );
}
